language: csharp

mono: none

dotnet: 2.1

script:
  - dotnet build ./lib/ArkEcosystem.Crypto
  - dotnet test ./tests/ArkEcosystem.Crypto.Tests/ArkEcosystem.Crypto.Tests.csproj

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1
